### ISSUE TITLE
作者大大，我对首页的数据渲染有疑问

### ISSUE THREAD

**Issue by JserJser** [se-rong/openshopping-vue#1]
作者大大，看到你的首页是由很多组件构成的，可是我没有发现数据是怎么渲染的啊，也没有看到说父组件通过props传参数给子组件啊？是我看错了吗？作者大大的项目很用心，很喜欢

**Comment by yrinleung** [comment]
感谢您的关注。
数据是通过接口返回，然后赋值给页面中的page。
详情请可以查看[https://github.com/yrinleung/openshopping-vue/blob/master/src/page/page/page.vue](https://github.com/yrinleung/openshopping-vue/blob/master/src/page/page/page.vue)中的created方法

**Comment by JserJser** [comment]
作者大大，你看我打印出返回来的结果
![image](https://user-images.githubusercontent.com/30041386/60696786-d0f18a00-9f19-11e9-8a2c-40e76d8d57e4.png)
也就是说，是将这些作为属性渲染到对应的组件
![image](https://user-images.githubusercontent.com/30041386/60696844-1615bc00-9f1a-11e9-8335-e90fb267224f.png)
我们以轮播广告页为例子:
![image](https://user-images.githubusercontent.com/30041386/60696881-3fcee300-9f1a-11e9-96a8-9acd4bcf645a.png)
这个代码里面没有向后端请求数据啊？可是却可以打印出结果来
![image](https://user-images.githubusercontent.com/30041386/60696983-99cfa880-9f1a-11e9-9c1f-bb7475e73dd0.png)

**Comment by yrinleung** [comment]
在[https://github.com/yrinleung/openshopping-vue/blob/master/src/page/page/page.vue](https://github.com/yrinleung/openshopping-vue/blob/master/src/page/page/page.vue)中的created方法获取页面组件的全部数据的，不是在每个组件中获取的。如：
```
 created:function(){
        GetPage().then(response=>{
            this.page=response;
        });
    },
```
在GetPage()获取整个页面组件的数据，然后在页面上循环给组件赋值：
```
<div v-for="(item,index) in page.Sections" :key="index">
        <imageAd v-if="item.Code=='ImageAd'" :data="item.ParameterDictionary"></imageAd>
 </div>
```

**Comment by JserJser** [comment]
作者大大棒棒哒，谢谢你鸭~

**Comment by yrinleung** [comment]
那我Close issue了。
再次感谢您的关注。
